name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Type check
        run: bun run typecheck

      - name: Smoke run (no dataset)
        run: |
          echo "[]" > tmp.dataset.json
          DATASET_PATH=tmp.dataset.json bun run src/index.ts > server.log 2>&1 &
          for i in {1..20}; do
            if curl -sSf http://localhost:3000 -o /dev/null; then
              echo "server ready"
              break
            fi
            sleep 1
          done
          curl -sSf http://localhost:3000 | head -c 200 || (echo "server failed to start — logs:" && cat server.log && exit 1)
        shell: bash
